import { Frame, Lines } from "./DiagramKit";

export default function C503KeyframeDiagram() {
  return (
    <Frame w={620} h={280} className="mx-auto w-full max-w-xl">
      <Lines x={310} y={20} lines={["Keyframe Animation Timeline"]} size={12} bold />
      <line x1="70" y1="140" x2="550" y2="140" stroke="currentColor" strokeWidth="2" />
      {[100,220,340,460,540].map((x,i)=><circle key={i} cx={x} cy={140} r={i===0||i===2||i===4?9:5} fill="currentColor" />)}
      <Lines x={100} y={115} lines={["K1"]} size={10} bold />
      <Lines x={340} y={115} lines={["K2"]} size={10} bold />
      <Lines x={540} y={115} lines={["K3"]} size={10} bold />
      <Lines x={310} y={205} lines={["Keyframes specify important states; intermediate frames can be generated by interpolation."]} size={10} />
    </Frame>
  );
}
